# Generated by Django 4.0.1 on 2022-03-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=20)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Experience', models.PositiveSmallIntegerField()),
                ('Speciality', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('DOI', models.DateField()),
                ('Reason', models.CharField(max_length=20)),
                ('Bed', models.CharField(max_length=20)),
                ('Blood_group', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('Age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
