# Generated by Django 4.0.1 on 2022-03-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='DOI',
            new_name='Appointment_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Reason',
            new_name='Decease',
        ),
    ]
