# Generated by Django 4.0.1 on 2022-03-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_doi_patient_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='Patient_name',
        ),
    ]
