# Generated by Django 4.0.1 on 2022-03-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_email_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Decease',
            new_name='Desease',
        ),
    ]
