# Generated by Django 4.0.1 on 2022-03-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_decease_patient_desease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Desease',
            new_name='Disease',
        ),
    ]
