# Generated by Django 4.0.1 on 2022-03-19 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_desease_patient_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
