# Generated by Django 4.0.1 on 2022-03-25 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Doctor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
