# Generated by Django 4.0.1 on 2022-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Doctor',
            field=models.CharField(max_length=50),
        ),
    ]
