# Generated by Django 4.0.1 on 2022-03-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_patient_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Doctor_name',
            field=models.CharField(max_length=50),
        ),
    ]
