# Generated by Django 4.0.1 on 2022-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_remove_patient_doctor_alter_patient_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bed_name', models.CharField(max_length=20)),
                ('Bed_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='Doctor_name',
            field=models.CharField(max_length=20),
        ),
    ]
