# Generated by Django 4.0.1 on 2022-03-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_bed_alter_patient_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='Bed_count',
            new_name='bed_count',
        ),
    ]
